"""Add a column in proof_revisions for content_schema_version

Revision ID: 2eff9d756471
Revises: d5115e972f06
Create Date: 2022-09-26 07:31:54.055506

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2eff9d756471'
down_revision = 'd5115e972f06'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('proof_revisions', sa.Column('content_schema_version', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('proof_revisions', 'content_schema_version')
    # ### end Alembic commands ###
